/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Cliente;
import java.awt.Component;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;


/**
 *
 * @author Angel
 */
public class PanelCliente extends javax.swing.JFrame {
    String usuarioLogueado;//para guardar el actual usuario logueado
    Boolean recargarchat;
    String tituloCancion;
    Cliente cli=new Cliente(this);
    JFileChooser fileSub=new JFileChooser();   
    JFileChooser fileDes=new JFileChooser();
    
    
    public PanelCliente() {
        initComponents();
        this.recargarchat=true;
        
       /* chat_global.setEnabled(false);
        chat_privado.setEnabled(false);
        btn_desconectar.setEnabled(false);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
       
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Panel_Pestanias = new javax.swing.JTabbedPane();
        conexion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        contrasenia = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        puerto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_acceder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        log_advertencia = new javax.swing.JTextArea();
        btn_desconectar = new javax.swing.JButton();
        selDirSubida = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        selDirBajada = new javax.swing.JButton();
        chat_global = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista_usuarios = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        caja_chatPublico = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        abrirPrivado = new javax.swing.JButton();
        hablar_publico = new javax.swing.JTextField();
        btnEnviarPublico = new javax.swing.JButton();
        btRefrescarLsuser = new javax.swing.JButton();
        chatearP2P = new javax.swing.JButton();
        chat_privado = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        caja_chatPrivado = new javax.swing.JTextArea();
        btnPlayCancion = new javax.swing.JButton();
        btnStopCancion = new javax.swing.JButton();
        hablar_privado = new javax.swing.JTextField();
        btn_enviar_privado = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lista_canciones = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        barraProgreso = new javax.swing.JProgressBar();
        jButton2 = new javax.swing.JButton();
        nombrePropietario = new javax.swing.JLabel();
        chateando_con = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        jLabel3.setText("Direccion");

        jLabel8.setText("Puerto");

        btn_acceder.setText("Conectar");
        btn_acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accederActionPerformed(evt);
            }
        });

        log_advertencia.setColumns(20);
        log_advertencia.setRows(5);
        jScrollPane1.setViewportView(log_advertencia);

        btn_desconectar.setText("Desconectar");
        btn_desconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desconectarActionPerformed(evt);
            }
        });

        selDirSubida.setText("Seleccionar directorio ...");
        selDirSubida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selDirSubidaActionPerformed(evt);
            }
        });

        jLabel10.setText("Carpeta para compartir:");

        jLabel11.setText("Carpeta de descarga :");

        selDirBajada.setText("Seleccionar directorio ...");
        selDirBajada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selDirBajadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout conexionLayout = new javax.swing.GroupLayout(conexion);
        conexion.setLayout(conexionLayout);
        conexionLayout.setHorizontalGroup(
            conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conexionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(conexionLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, conexionLayout.createSequentialGroup()
                        .addGroup(conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, conexionLayout.createSequentialGroup()
                                .addComponent(btn_acceder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(btn_desconectar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, conexionLayout.createSequentialGroup()
                                .addGroup(conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(contrasenia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(direccion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(puerto, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usuario))))
                        .addGap(123, 252, Short.MAX_VALUE)
                        .addGroup(conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selDirSubida)
                            .addComponent(jLabel10)
                            .addComponent(selDirBajada)
                            .addComponent(jLabel11))
                        .addGap(166, 166, 166))))
        );
        conexionLayout.setVerticalGroup(
            conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(conexionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, conexionLayout.createSequentialGroup()
                        .addGroup(conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(conexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_acceder)
                            .addComponent(btn_desconectar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, conexionLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selDirSubida)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selDirBajada)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        Panel_Pestanias.addTab("Conexion", conexion);

        chat_global.setEnabled(false);

        lista_usuarios.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Nadie conectado." };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lista_usuarios);

        jLabel4.setText("Lista de usuarios privados :");

        caja_chatPublico.setColumns(20);
        caja_chatPublico.setRows(5);
        jScrollPane3.setViewportView(caja_chatPublico);

        jLabel5.setText("Chat publico:");

        abrirPrivado.setText("Chatear ");
        abrirPrivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirPrivadoActionPerformed(evt);
            }
        });

        hablar_publico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hablar_publicoActionPerformed(evt);
            }
        });

        btnEnviarPublico.setText("Enviar");
        btnEnviarPublico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarPublicoActionPerformed(evt);
            }
        });

        btRefrescarLsuser.setText("Refrescar");
        btRefrescarLsuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRefrescarLsuserActionPerformed(evt);
            }
        });

        chatearP2P.setText("Chatear P2P");
        chatearP2P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatearP2PActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout chat_globalLayout = new javax.swing.GroupLayout(chat_global);
        chat_global.setLayout(chat_globalLayout);
        chat_globalLayout.setHorizontalGroup(
            chat_globalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chat_globalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chat_globalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chat_globalLayout.createSequentialGroup()
                        .addComponent(hablar_publico, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviarPublico))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(chat_globalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chat_globalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addComponent(chatearP2P, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chat_globalLayout.createSequentialGroup()
                        .addComponent(abrirPrivado, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btRefrescarLsuser, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        chat_globalLayout.setVerticalGroup(
            chat_globalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chat_globalLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(chat_globalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chat_globalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(chat_globalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chat_globalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hablar_publico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEnviarPublico))
                    .addComponent(chatearP2P))
                .addGap(11, 11, 11)
                .addGroup(chat_globalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(abrirPrivado)
                    .addComponent(btRefrescarLsuser))
                .addGap(66, 66, 66))
        );

        Panel_Pestanias.addTab("Chat global", chat_global);

        chat_privado.setEnabled(false);

        caja_chatPrivado.setColumns(20);
        caja_chatPrivado.setRows(5);
        jScrollPane5.setViewportView(caja_chatPrivado);

        btnPlayCancion.setText("Play");
        btnPlayCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayCancionActionPerformed(evt);
            }
        });

        btnStopCancion.setText("Stop");

        btn_enviar_privado.setText("Enviar");
        btn_enviar_privado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviar_privadoActionPerformed(evt);
            }
        });

        jLabel6.setText("Lista de canciones:");

        jLabel7.setText("Conversación:");

        jScrollPane6.setViewportView(lista_canciones);

        jLabel9.setText("Progreso:");

        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        nombrePropietario.setText("Propietario:");

        chateando_con.setText("Chatenado con:");

        javax.swing.GroupLayout chat_privadoLayout = new javax.swing.GroupLayout(chat_privado);
        chat_privado.setLayout(chat_privadoLayout);
        chat_privadoLayout.setHorizontalGroup(
            chat_privadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chat_privadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chat_privadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(chat_privadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(chat_privadoLayout.createSequentialGroup()
                            .addComponent(btnPlayCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnStopCancion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(chat_privadoLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(barraProgreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nombrePropietario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(chat_privadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                    .addGroup(chat_privadoLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(chat_privadoLayout.createSequentialGroup()
                        .addComponent(chateando_con)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreUsuario)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(chat_privadoLayout.createSequentialGroup()
                        .addComponent(hablar_privado, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(btn_enviar_privado)))
                .addContainerGap())
        );
        chat_privadoLayout.setVerticalGroup(
            chat_privadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chat_privadoLayout.createSequentialGroup()
                .addGroup(chat_privadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrePropietario)
                    .addComponent(chateando_con)
                    .addComponent(nombreUsuario))
                .addGap(8, 8, 8)
                .addGroup(chat_privadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(chat_privadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addGap(18, 18, 18)
                .addGroup(chat_privadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(barraProgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(chat_privadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hablar_privado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_enviar_privado)))
                .addGap(18, 18, 18)
                .addGroup(chat_privadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStopCancion)
                    .addComponent(btnPlayCancion))
                .addGap(34, 34, 34))
        );

        Panel_Pestanias.addTab("nombre del usuario", chat_privado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Pestanias)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Pestanias)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Set para los campos
    
    public void setCajaChatGrupal(String cadena){
        caja_chatPublico.append(cadena+"\n");
    }
    
    public void setCajaChatIndividual(String cadena){
        caja_chatPrivado.append(cadena+"\n");
    }
    
    public void setListaUsuarios(DefaultListModel lista){
        lista_usuarios.setModel(lista);
    }
    
    public void setListaCanciones(DefaultListModel lista){
        lista_canciones.setModel(lista);
    }
    
    public void setLog(String cadena){
        log_advertencia.append(cadena+"\n");
    }

    public JButton getBtn_acceder() {
        return btn_acceder;
    }

    public JTextField getContrasenia() {
        return contrasenia;
    }

    public JTextField getDireccion() {
        return direccion;
    }

    public JTextField getPuerto() {
        return puerto;
    }

    public JTextField getUsuario() {
        return usuario;
    }
    
    public JTabbedPane getPanelPestanias(){
        return Panel_Pestanias;
    }
    
    public JPanel getChatPrivado(){
        return chat_privado;
    }
    
    public JPanel getChatPublico(){
        return chat_global;
    }

    public JLabel getNombreUsuario() {
        return nombreUsuario;
    }

    public JLabel getNombrePropietario() {
        return nombrePropietario;
    }

    public void setNombrePropietario(String nombrePropietario) {
        this.nombrePropietario.setText(nombrePropietario);
    }

    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario.setText(nombreUsuario);
    }
        
    public JButton getBtn_desconectar(){
        return btn_desconectar;
    }

    public JProgressBar getBarraProgreso() {
        return barraProgreso;
    }

    public void setBarraProgreso(int num) {
        this.barraProgreso.setValue(num);
    }
    
    
    
    private void hablar_publicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hablar_publicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hablar_publicoActionPerformed

    //Lista de usuarios 
    private void abrirPrivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirPrivadoActionPerformed
        Object seleccion = lista_usuarios.getSelectedValue();//Sacamos el valor
        String usuarioSeleccionado=seleccion.toString(); //Escogemos el usuario seleccionado
        cli.iniciarChatPrivado(usuarioSeleccionado);//abrimos el chat
        cli.getMultimedia().pedirListaCanciones(usuarioSeleccionado);//pedimos la lista de canciones
        nombreUsuario.setText(usuarioSeleccionado);
        nombrePropietario.setText(usuarioLogueado);//mostramos el usuario con el que nos hemos logueado
        Panel_Pestanias.addTab(usuarioSeleccionado,null, chat_privado);//Nombre de la pestaña,null,nombre del panel en donde vamos agregar*/
    }//GEN-LAST:event_abrirPrivadoActionPerformed
        
    
    private void btn_accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accederActionPerformed
        this.cli=new Cliente(this);
        cli.conexion(direccion.getText(),
                Integer.parseInt(puerto.getText()),
                usuario.getText(),
                contrasenia.getText());
        usuarioLogueado=usuario.getText();//Guardamos el usuario logueado
        cli.start();//Iniciamos la hebra de cliente
        cli.login();
        cli.pedirListaUsuarios();
        
        //Para los directorios
        cli.getMultimedia().setDirectorioSubida(fileSub);
        cli.getMultimedia().setDirectorioBajada(fileDes);
    }//GEN-LAST:event_btn_accederActionPerformed
   
    private void btn_desconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desconectarActionPerformed
        cli.desconectar();
    }//GEN-LAST:event_btn_desconectarActionPerformed

    private void btnEnviarPublicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarPublicoActionPerformed
       caja_chatPublico.append("YO -> "+hablar_publico.getText()+"\n");        
       cli.hablarChatGrupal(hablar_publico.getText());
    }//GEN-LAST:event_btnEnviarPublicoActionPerformed
    
    //Para refrescar  la lista de usuarios
    private void btRefrescarLsuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRefrescarLsuserActionPerformed
        cli.pedirListaUsuarios();//Pedimos lista de de usuarios
    }//GEN-LAST:event_btRefrescarLsuserActionPerformed

    private void btn_enviar_privadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviar_privadoActionPerformed
        caja_chatPrivado.append("YO -> "+hablar_privado.getText()+"\n");
        cli.hablarChatPrivado(hablar_privado.getText(),nombreUsuario.getText());
    }//GEN-LAST:event_btn_enviar_privadoActionPerformed

    private void btnPlayCancionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayCancionActionPerformed
        Object seleccion = lista_canciones.getSelectedValue();//Sacamos el valor
        this.tituloCancion=seleccion.toString(); //Escogemos el usuario seleccionado
        //Formato  titulo de la cancion,usuario propietario,usuario al que pedimos la cancion
        
        cli.getMultimedia().iniciarReproduccion(this.tituloCancion,this.usuarioLogueado,this.nombreUsuario.getText());
    }//GEN-LAST:event_btnPlayCancionActionPerformed

    private void selDirSubidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selDirSubidaActionPerformed
        fileSub=new JFileChooser();
        fileSub.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileSub.setDialogTitle("Selecciona un directorio");
        fileSub.showOpenDialog(this);
    }//GEN-LAST:event_selDirSubidaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Component selected = Panel_Pestanias.getSelectedComponent();
        if (selected != null) {
            Panel_Pestanias.remove(selected);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void selDirBajadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selDirBajadaActionPerformed
        // TODO add your handling code here:
        fileDes=new JFileChooser();
        fileDes.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fileDes.setDialogTitle("Selecciona un directorio");
        fileDes.showOpenDialog(this);
    }//GEN-LAST:event_selDirBajadaActionPerformed

    private void chatearP2PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatearP2PActionPerformed
        //Sacamos el usuario seleccionado
        Object seleccion = lista_usuarios.getSelectedValue();//Sacamos el valor
        String usuarioSeleccionado=seleccion.toString(); //Escogemos el usuario seleccionado
        cli.inciarConexionChatP2P(usuarioSeleccionado);//para empezar el hilo con el chat privado
    }//GEN-LAST:event_chatearP2PActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
                       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run(){
                new PanelCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Panel_Pestanias;
    private javax.swing.JButton abrirPrivado;
    private javax.swing.JProgressBar barraProgreso;
    private javax.swing.JButton btRefrescarLsuser;
    private javax.swing.JButton btnEnviarPublico;
    private javax.swing.JButton btnPlayCancion;
    private javax.swing.JButton btnStopCancion;
    private javax.swing.JButton btn_acceder;
    private javax.swing.JButton btn_desconectar;
    private javax.swing.JButton btn_enviar_privado;
    private javax.swing.JTextArea caja_chatPrivado;
    private javax.swing.JTextArea caja_chatPublico;
    private javax.swing.JPanel chat_global;
    private javax.swing.JPanel chat_privado;
    private javax.swing.JLabel chateando_con;
    private javax.swing.JButton chatearP2P;
    private javax.swing.JPanel conexion;
    private javax.swing.JTextField contrasenia;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField hablar_privado;
    private javax.swing.JTextField hablar_publico;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JList lista_canciones;
    private javax.swing.JList lista_usuarios;
    private javax.swing.JTextArea log_advertencia;
    private javax.swing.JLabel nombrePropietario;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JTextField puerto;
    private javax.swing.JButton selDirBajada;
    private javax.swing.JButton selDirSubida;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}